development:
  adapter: postgresql
  encoding: utf8
  database: runewords_api_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: runewords_api_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: runewords_api_production
  pool: 5
  username:
  password:
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
